services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: nestapp
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tecnodiniz
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
